# This is a basic workflow to help you get started with Actions

name: CI


on:
  push:
    branches: [ main, refactor ] # TODO SPLIT ACTIONS
    # TODO ADD RELEASE and RELEASE TIME
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3


      - name: Test
        run: |
          pip install -r requirements.dev.txt
          pytest
      - name: yc install
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
      - name: Update Release
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
          AWS_BUCKET: ${{secrets.AWS_BUCKET}}
          IAM_TOKEN: ${{secrets.IAM_TOKEN}}
          PAYMENT_TOKEN: ${{secrets.PAYMENT_TOKEN}}
        run: | 
          zip release.zip -r ./src/* requirements.txt -x '*.pyc' '*__pycache__*'
          aws --endpoint-url=https://storage.yandexcloud.net s3 cp release.zip s3://${AWS_BUCKET}/
          /home/runner/yandex-cloud/bin/yc config set token ${IAM_TOKEN} 
          /home/runner/yandex-cloud/bin/yc serverless function version create --function-name=menu --runtime python39 --entrypoint src.v1_index.entry_point --memory 128mb --execution-timeout 5s --source-path ./release.zip --folder-id b1gs53dk9tg8j64f05uu --environment payment_token=${PAYMENT_TOKEN}